[SDFSDF]
[modules]
Do_A_Thing = { git.asd = 'git@github.com:sjorsdonkers/modocil.git', commit = '21a0e57', path = 'examples/assets/Do_A_Thing.jai' }
Do_Other_Thing = { git = 'git@github.com:sjorsdonkers/modocil.git', path = 'examples/assets/Do_Other_Thing' }

# Mixed-type arrays are allowed
numbers = [ 0, 0, 0, 1, 2, 5 ]
contributors = [
  'Foo Bar <foo@example.com>',
  { name = 'Baz Qux', email = 'bazqux@example.com', url = 'https://example.com/bazqux' }
]

a.b = [
  {b.c = 3, b.d = 7},
  {b.c = 3, b.d = 7},
]

[[products]]
name = 'Hammer'
sku = 738594937

[[products]]  # empty table within the array

[[products]]
name = 'Nail'
sku = 284758393

color = 'gray'


[sdf]
ffff = [[4, 5, 6], [7, 8, 9]]

'' = 'blank'
2fruit . 'flavor' = {'banana' .ok = 'yes'}

int1 = +99
int2 = 42
int3 = 0
int4 = -17
int5 = 1_000
int6 = 5_349_221
int7 = 53_49_221  # Indian number system grouping
int8 = 1_2_3_4_5
# hexadecimal with prefix `0x`
hex1 = 0xDEADBEEF
hex2 = 0xdeadbeef
hex3 = 0xdead_beef
# octal with prefix `0o`
oct1 = 0o01234567
oct2 = 0o755 # useful for Unix file permissions
# binary with prefix `0b`
bin1 = 0b11010110
